#Site settings
title: Una suma estudiantil. 
author: Luis Gerardo Parra Cayetano 
 name: Luis Gerardo Parra Cayetano 
 email: gerardoparracayetano@gmail.com
description: Un proyecto sobre la transmisión de filosofía en el medievo. 
